.\"	Copyright (c) 2021 Benjamin Baier <ben@netzbasis.de>
.\"
.\"	Permission to use, copy, modify, and distribute this software for any
.\"	purpose with or without fee is hereby granted, provided that the above
.\"	copyright notice and this permission notice appear in all copies.
.\"
.\"	THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\"	WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\"	MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\"	ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\"	WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\"	ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\"	OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: February 1 2021 $
.Dt SNDGEN 1
.Os
.Sh NAME
.Nm sndgen
.Nd generate sound
.Sh SYNOPSIS
.Nm sndgen
.Op Fl clr
.Op Fl d Ar delay
.Op Fl s Ar hz
.Sh DESCRIPTION
.Nm
is used to generate stereo sound and directly play it using sndiod(8).
The default output is white noise.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl c
Play a chirp sound.
.It Fl d Ar delay
Add delay between samples.
.It Fl l
Only play the left channel.
.It Fl r
Only play the right channel.
.It Fl s Ar hz
Play a sine wave at the specified frequency.
.El
.Sh SEE ALSO
.Xr aucat 1 ,
.Xr sndiod 8 ,
.Xr sio_open 3
